language: objective-c
osx_image: xcode9.1

xcode_project: GTTexture-RxExtension.xcworkspace 
xcode_scheme:  GTTexture-RxExtensionTests

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master