language: objective-c
osx_image: xcode9.1

xcode_scheme:  GTTexture-RxExtensionTests
xcode_workspace: GTTexture-RxExtension.xcworkspace 

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master